[pytest]
addopts = -v --headed --html=reports/report.html --self-contained-html
# --headed odpali testy przeglądarki ze zwykłym oknem graficznym (żebyś widział, co się dzieje).
# Aby odpalać w tle (headless), usuń --headed.
# --html=reports/report.html generuje raport HTML po każdym uruchomieniu testów.
# --self-contained-html pakuje CSS/JS do jednego pliku .html (łatwiejszy do udostępnienia).
pythonpath = . 
# To pozwala łatwiej importować pliki z pages w tests
